version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        uid: ${UID:-1000}
        gid: ${GID:-1000}
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
       - "3307:3306" 
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
      - ./docker-compose/mysql/init.sql:/docker-entrypoint-initdb.d/testdatabase.sql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge